name: application
description: "A new Flutter Project"
publish_to: "none"
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.0.0
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  group_button: ^5.3.4
  iconsax: ^0.0.8
  infinite_carousel: ^1.1.1
  intl: ^0.19.0
  loader_overlay: ^4.0.0
  numberpicker: ^2.1.2
  simple_grid: ^0.1.5
  sizer: ^2.0.15
  syncfusion_flutter_gauges: ^25.1.37
  unicons: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

